# setting_db.py
columns_sellers = """
            supplierId INT PRIMARY KEY,
            bin VARCHAR(255),
            inn BIGINT,
            kpp VARCHAR(255),
            ogrnip BIGINT,
            supplierFullName VARCHAR(255),
            supplierName VARCHAR(255),
            taxpayerCode BIGINT,
            trademark VARCHAR(255),
            unn VARCHAR(255),
            unp VARCHAR(255),
            datetime_check DATE
            """

# DB_GOODS
columns_goods = """
            id INT PRIMARY KEY,
            supplierId INT,
            __sort INT,
            brand VARCHAR(255),
            brandId INT,
            colors JSONB,
            diffPrice BOOLEAN,
            dist INT,
            dtype INT,
            feedbacks INT,
            kindId INT,
            ksort INT,
            log JSONB,
            logisticsCost INT,
            name VARCHAR(255),
            panelPromoId INT,
            pics INT,
            priceU INT,
            promoTextCard VARCHAR(255),
            promoTextCat VARCHAR(255),
            rating INT,
            returnCost INT,
            reviewRating FLOAT,
            root INT,
            sale INT,
            saleConditions INT,
            salePriceU INT,
            siteBrandId INT,
            sizes JSONB,
            subjectId INT,
            subjectParentId INT,
            supplier VARCHAR(255),
            supplierFlags INT,
            supplierRating FLOAT,
            time1 INT,
            time2 INT,
            viewFlags INT,
            isNew VARCHAR(255),
            volume INT,
            wh INT
            """